export const NATIONALITIES_LIST = 'NATIONALITIES_LIST';
export const NATIONALITIES_LIST_PENDING = 'NATIONALITIES_LIST_PENDING';
export const NATIONALITIES_LIST_FULFILLED = 'NATIONALITIES_LIST_FULFILLED';
export const NATIONALITIES_LIST_REJECTED = 'NATIONALITIES_LIST_REJECTED';

export const list = () => ({
    type: NATIONALITIES_LIST,
});
